import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Header from "@/components/layout/Header";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
  // No need to specify weight - supports 200-900 automatically
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${nunito.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
